import * as crypto from "crypto";
import config from "./config";

export interface AltchaChallenge {
    algorithm: "SHA-256";
    challenge: string;
    salt: string;
    signature: string;
    maxNumber?: number;
}

/**
 * Creates an ALTCHA cryptographic challenge payload.
 */
export function createAltchaChallenge(maxNumber = 100000): AltchaChallenge {
    const hmacKey = config.altcha.hmacKey || "default-altcha-secret";
    const number = Math.floor(Math.random() * maxNumber);
    const salt = crypto.randomBytes(16).toString("hex");
    
    // Hash salt + number to create the challenge
    const challenge = crypto.createHash("sha256").update(salt + number).digest("hex");
    
    // Signature certifies that this challenge was generated by our server
    const signature = crypto.createHmac("sha256", hmacKey)
        .update(salt + challenge)
        .digest("hex");

    return {
        algorithm: "SHA-256",
        challenge,
        salt,
        signature,
        maxNumber
    };
}

/**
 * Verifies a solved ALTCHA cryptographic challenge.
 */
export function verifyAltchaSolution(payload: {
    challenge: string;
    salt: string;
    number: number;
    signature: string;
}): boolean {
    // If ALTCHA is disabled in config, skip checks and return true
    if (!config.altcha.enabled) {
        return true;
    }

    const { challenge, salt, number, signature } = payload;
    const hmacKey = config.altcha.hmacKey || "default-altcha-secret";

    if (!challenge || !salt || number === undefined || !signature) {
        return false;
    }

    // 1. Verify the challenge signature
    const expectedSignature = crypto.createHmac("sha256", hmacKey)
        .update(salt + challenge)
        .digest("hex");

    if (signature !== expectedSignature) {
        return false;
    }

    // 2. Verify the proof-of-work (that salt + number hashes to the challenge)
    const expectedChallenge = crypto.createHash("sha256")
        .update(salt + number)
        .digest("hex");

    return challenge === expectedChallenge;
}
