import { describe, it, expect, vi, beforeEach } from 'vitest';
import { 
    verifyNinAction, 
    getAdmissionEngineSetting, 
    saveAdmissionEngineSetting, 
    updateSectionsOrder 
} from '../../actions/admission_v2';
import { db } from '@/db/db';

vi.mock('next/cache', () => ({
    revalidatePath: vi.fn(),
}));

describe('Admission Engine Actions', () => {
    beforeEach(() => {
        vi.clearAllMocks();
    });

    describe('verifyNinAction', () => {
        it('should return error for empty or invalid length NIN', async () => {
            const result1 = await verifyNinAction('');
            expect(result1.success).toBe(false);
            expect(result1.error).toContain('NIN must be exactly 11 numeric digits.');

            const result2 = await verifyNinAction('12345');
            expect(result2.success).toBe(false);
            expect(result2.error).toContain('NIN must be exactly 11 numeric digits.');
        });

        it('should return error for non-numeric NIN', async () => {
            const result = await verifyNinAction('1234567890a');
            expect(result.success).toBe(false);
            expect(result.error).toContain('NIN must be exactly 11 numeric digits.');
        });

        it('should return mock database details for a known registered NIN', async () => {
            const result = await verifyNinAction('12345678901');
            expect(result.success).toBe(true);
            expect(result.verifiedName).toBe('Abubakar Alao');
            expect(result.firstName).toBe('Abubakar');
            expect(result.lastName).toBe('Alao');
            expect(result.dob).toBe('2010-05-15');
            expect(result.gender).toBe('Male');
        });

        it('should return autogenerated mock details for an unknown but valid 11-digit NIN', async () => {
            const result = await verifyNinAction('99999999999');
            expect(result.success).toBe(true);
            expect(result.verifiedName).toBe('Verified Applicant-9999');
            expect(result.firstName).toBe('Verified');
            expect(result.lastName).toBe('Applicant-9999');
            expect(result.dob).toBe('2010-01-01');
            expect(result.gender).toBe('Female');
        });
    });

    describe('getAdmissionEngineSetting', () => {
        it('should return active admission engine setting or default to multi_level', async () => {
            (db.select as any).mockReturnValue({
                from: vi.fn(() => ({
                    where: vi.fn(() => ({
                        limit: vi.fn().mockResolvedValue([{ settingValue: 'jamb_only' }])
                    }))
                }))
            });

            const result = await getAdmissionEngineSetting();
            expect(result).toBe('jamb_only');
        });

        it('should fallback to multi_level on error', async () => {
            (db.select as any).mockImplementation(() => {
                throw new Error('Database connection failed');
            });

            const result = await getAdmissionEngineSetting();
            expect(result).toBe('multi_level');
        });
    });

    describe('saveAdmissionEngineSetting', () => {
        it('should insert system setting if not already present', async () => {
            // Mock empty select result
            (db.select as any).mockReturnValue({
                from: vi.fn(() => ({
                    where: vi.fn(() => ({
                        limit: vi.fn().mockResolvedValue([])
                    }))
                }))
            });

            const mockInsertValues = vi.fn().mockResolvedValue([{}]);
            (db.insert as any).mockReturnValue({
                values: mockInsertValues
            });

            const result = await saveAdmissionEngineSetting('direct_only');
            expect(result.success).toBe(true);
            expect(db.insert).toHaveBeenCalled();
            expect(mockInsertValues).toHaveBeenCalledWith(expect.objectContaining({
                settingKey: 'active_admission_engine',
                settingValue: 'direct_only'
            }));
        });

        it('should update system setting if already present', async () => {
            // Mock existing select result
            (db.select as any).mockReturnValue({
                from: vi.fn(() => ({
                    where: vi.fn(() => ({
                        limit: vi.fn().mockResolvedValue([{ id: 1, settingValue: 'multi_level' }])
                    }))
                }))
            });

            const mockUpdateSet = vi.fn().mockReturnValue({
                where: vi.fn().mockResolvedValue([{}])
            });
            (db.update as any).mockReturnValue({
                set: mockUpdateSet
            });

            const result = await saveAdmissionEngineSetting('jamb_only');
            expect(result.success).toBe(true);
            expect(db.update).toHaveBeenCalled();
            expect(mockUpdateSet).toHaveBeenCalledWith(expect.objectContaining({
                settingValue: 'jamb_only'
            }));
        });
    });

    describe('updateSectionsOrder', () => {
        it('should perform transaction and update order of all elements', async () => {
            const mockUpdate = vi.fn().mockReturnValue({
                set: vi.fn().mockReturnValue({
                    where: vi.fn().mockResolvedValue([])
                })
            });

            db.transaction = vi.fn().mockImplementation(async (cb) => {
                const mockTx = { update: mockUpdate };
                return await cb(mockTx);
            });

            const sections = [
                { id: 101, order: 1 },
                { id: 102, order: 2 }
            ];

            const result = await updateSectionsOrder(sections, 1);
            expect(result.success).toBe(true);
            expect(db.transaction).toHaveBeenCalled();
            expect(mockUpdate).toHaveBeenCalledTimes(2);
        });

        it('should return error on failure', async () => {
            db.transaction = vi.fn().mockImplementation(async () => {
                throw new Error('Transaction aborted');
            });

            const result = await updateSectionsOrder([], 1);
            expect(result.success).toBe(false);
            expect(result.error).toBe('Failed to save pages order');
        });
    });
});
